name: Doc Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  doc_coverage:
    name: Check Doc Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydocstyle

      - name: Check Docstring Coverage
        run: |
          pydocstyle --count src/tenx_auto_grade/pipelines/
